[2023-01-30T12:19:00.358+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.mirror_flights manual__2023-01-30T12:18:59.521768+00:00 [queued]>
[2023-01-30T12:19:00.365+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.mirror_flights manual__2023-01-30T12:18:59.521768+00:00 [queued]>
[2023-01-30T12:19:00.365+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:19:00.366+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T12:19:00.366+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:19:00.374+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): mirror_flights> on 2023-01-30 12:18:59.521768+00:00
[2023-01-30T12:19:00.380+0000] {standard_task_runner.py:55} INFO - Started process 15685 to run task
[2023-01-30T12:19:00.383+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'mirror_flights', 'manual__2023-01-30T12:18:59.521768+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpoc6yy8k0']
[2023-01-30T12:19:00.384+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask mirror_flights
[2023-01-30T12:19:00.438+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.mirror_flights manual__2023-01-30T12:18:59.521768+00:00 [running]> on host f9ad67e64070
[2023-01-30T12:19:00.486+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=mirror_flights
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T12:18:59.521768+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T12:18:59.521768+00:00
[2023-01-30T12:19:01.168+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table mrr_flights because other objects depend on it
DETAIL:  view analysis.mrr_flights depends on table mrr_flights
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simple_dag.py", line 20, in get_flights
    df.to_sql('mrr_flights', connect_to_db(),if_exists='replace',index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 1102, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_ddl
    compiled,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table mrr_flights because other objects depend on it
DETAIL:  view analysis.mrr_flights depends on table mrr_flights
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE mrr_flights]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-01-30T12:19:01.182+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=mirror_flights, execution_date=20230130T121859, start_date=20230130T121900, end_date=20230130T121901
[2023-01-30T12:19:01.190+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task mirror_flights ((psycopg2.errors.DependentObjectsStillExist) cannot drop table mrr_flights because other objects depend on it
DETAIL:  view analysis.mrr_flights depends on table mrr_flights
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE mrr_flights]
(Background on this error at: https://sqlalche.me/e/14/2j85); 15685)
[2023-01-30T12:19:01.226+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-30T12:19:01.244+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
