[2023-01-31T00:00:01.287+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step scheduled__2023-01-30T00:00:00+00:00 [queued]>
[2023-01-31T00:00:01.293+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step scheduled__2023-01-30T00:00:00+00:00 [queued]>
[2023-01-31T00:00:01.293+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T00:00:01.294+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-31T00:00:01.294+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T00:00:01.302+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-30 00:00:00+00:00
[2023-01-31T00:00:01.308+0000] {standard_task_runner.py:55} INFO - Started process 3267 to run task
[2023-01-31T00:00:01.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'scheduled__2023-01-30T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmp16dvtxns']
[2023-01-31T00:00:01.312+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask dbt_step
[2023-01-31T00:00:01.362+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step scheduled__2023-01-30T00:00:00+00:00 [running]> on host 4d49ce0454d7
[2023-01-31T00:00:01.409+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-30T00:00:00+00:00
[2023-01-31T00:00:01.412+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-31T00:00:01.413+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2023-01-31T00:00:01.426+0000] {subprocess.py:86} INFO - Output:
[2023-01-31T01:06:23.717+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-31T01:06:23.721+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3267. PIDs of all processes in the group: [3268, 3269, 3267]
[2023-01-31T01:06:23.722+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3267
[2023-01-31T01:06:23.723+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-31T01:06:23.724+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-01-31T01:06:23.776+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3267, status='terminated', exitcode=0, started='00:00:00') (3267) terminated with exit code 0
[2023-01-31T01:06:23.777+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3269, status='terminated', started='00:00:01') (3269) terminated with exit code None
[2023-01-31T01:06:23.778+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3268, status='terminated', started='00:00:00') (3268) terminated with exit code None
